-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS DB_SCRAPE;

-- Criação do schema
CREATE SCHEMA IF NOT EXISTS DB_SCRAPE.SC_SCRAPE;

-- Criação da tabela 
 
CREATE OR REPLACE TABLE DB_SCRAPE.SC_SCRAPE.TB_BOOKS_TO_SCRAPE (
    id INTEGER ,
    title STRING,
    price FLOAT,
    rating INTEGER,
    availability STRING,
    category STRING,
    image_url STRING,
    METADATA_FILENAME STRING,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
);

-- Criação dos usuários
CREATE USER IF NOT EXISTS amilton_faria PASSWORD = 'alterado' DEFAULT_ROLE = PUBLIC MUST_CHANGE_PASSWORD = TRUE;
CREATE USER IF NOT EXISTS fernando_bastos PASSWORD = 'alterado' DEFAULT_ROLE = PUBLIC MUST_CHANGE_PASSWORD = TRUE;
CREATE USER IF NOT EXISTS lucas_zago PASSWORD = 'alterado' DEFAULT_ROLE = PUBLIC MUST_CHANGE_PASSWORD = TRUE;
CREATE USER IF NOT EXISTS rodrigo_telles PASSWORD = 'alterado' DEFAULT_ROLE = PUBLIC MUST_CHANGE_PASSWORD = TRUE;

-- Grants de acesso ao banco e schema
CREATE ROLE IF NOT EXISTS ROLE_BOOKS_SCRAPE;

GRANT USAGE ON DATABASE DB_SCRAPE TO ROLE ROLE_BOOKS_SCRAPE;
GRANT USAGE ON SCHEMA DB_SCRAPE.SC_SCRAPE TO ROLE ROLE_BOOKS_SCRAPE;
GRANT CREATE TABLE ON SCHEMA DB_SCRAPE.SC_SCRAPE TO ROLE ROLE_BOOKS_SCRAPE;
GRANT SELECT ON ALL TABLES IN SCHEMA DB_SCRAPE.SC_SCRAPE TO ROLE ROLE_BOOKS_SCRAPE;
GRANT INSERT ON ALL TABLES IN SCHEMA DB_SCRAPE.SC_SCRAPE TO ROLE ROLE_BOOKS_SCRAPE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DB_SCRAPE.SC_SCRAPE TO ROLE ROLE_BOOKS_SCRAPE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_BOOKS_SCRAPE;

GRANT ROLE ROLE_BOOKS_SCRAPE TO USER amilton_faria;
GRANT ROLE ROLE_BOOKS_SCRAPE TO USER fernando_bastos;
GRANT ROLE ROLE_BOOKS_SCRAPE TO USER lucas_zago;
GRANT ROLE ROLE_BOOKS_SCRAPE TO USER rodrigo_telles;

ALTER USER amilton_faria SET DEFAULT_WAREHOUSE = COMPUTE_WH;
ALTER USER fernando_bastos SET DEFAULT_WAREHOUSE = COMPUTE_WH;
ALTER USER lucas_zago SET DEFAULT_WAREHOUSE = COMPUTE_WH;
ALTER USER rodrigo_telles SET DEFAULT_WAREHOUSE = COMPUTE_WH;



ALTER USER amilton_faria SET DEFAULT_NAMESPACE = DB_SCRAPE.SC_SCRAPE;
ALTER USER fernando_bastos SET DEFAULT_NAMESPACE = DB_SCRAPE.SC_SCRAPE;
ALTER USER lucas_zago SET DEFAULT_NAMESPACE = DB_SCRAPE.SC_SCRAPE;
ALTER USER rodrigo_telles SET DEFAULT_NAMESPACE = DB_SCRAPE.SC_SCRAPE;


ALTER USER rodrigo_telles SET PASSWORD = 'alterado';


GRANT USAGE ON FILE FORMAT DB_SCRAPE.SC_SCRAPE.CSV_FILEFORMAT TO ROLE ROLE_BOOKS_SCRAPE;
GRANT USAGE ON SCHEMA DB_SCRAPE.SC_SCRAPE TO ROLE_BOOKS_SCRAPE;
GRANT OPERATE ON PIPE DB_SCRAPE.SC_SCRAPE.PIPE_BOOKS_TO_SCRAPE TO ROLE_BOOKS_SCRAPE;